### PR TITLE
Fix compatibility with Kimai 1.10

### PR DESCRIPTION
**Pull request by kulturbande**

### CODE REVIEW

**Comment by kulturbande** [comment]
Version 1.10 leads to the number 11 in the following comparison and that is lower than 16. So it is not possible to import time values with the latest version of Kimai.

**Review by kevinpapst — APPROVED** [review]
One character bugs are the best ... 😁 Good to know that somebody actually uses the plugin.

Thanks for the bugfix!

**Comment by kulturbande** [comment]
Well, I try out GrandTotal at the moment and had this behavior. I'm looking for a good accounting solution as an addition to Kimai.

**Comment by kevinpapst** [comment]
If you choose another one and you need a connector to Kimai, please let me know in the main repository.
I am interested in extending 3rd party support, as this should greatly improve the usability of Kimai.

**Comment by kulturbande** [comment]
I tried to update the plugin, but it didn't worked. Is it required to rebuild the given zip file?

**Comment by kevinpapst** [comment]
If I remember correctly: zip the plugin directory and then simply double-click it in Finder. 
Should be documented in README...

**Pull request merged**
